package com.dnoel.checklistv1

import androidx.room.Room
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import org.robolectric.annotation.Config

/**
 * Exercises the *real* Room-generated DAOs against an in-memory SQLite database.
 *
 * [ListsViewModelTest] and [ChecklistViewModelTest] use hand-written fakes, which
 * verify the ViewModels but say nothing about whether the SQL in [ListDao] and
 * [ChecklistDao] is correct — a fake reproduces what we *assumed* the query does.
 * These tests run the actual statements, so a wrong ORDER BY, a broken GROUP BY,
 * or a missing cascade fails here.
 *
 * Robolectric provides an Android context on the JVM, so these run inside the
 * normal `testDebugUnitTest` task — no device, and CI picks them up for free.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class DaoTest {

    private lateinit var db: AppDatabase
    private lateinit var listDao: ListDao
    private lateinit var checklistDao: ChecklistDao

    @Before
    fun createDatabase() {
        db = Room.inMemoryDatabaseBuilder(
            RuntimeEnvironment.getApplication(),
            AppDatabase::class.java
        ).build()
        listDao = db.listDao()
        checklistDao = db.checklistDao()
    }

    @After
    fun closeDatabase() {
        db.close()
    }

    // --- ListDao -----------------------------------------------------------

    @Test
    fun `getAll returns lists ordered by position, not by insertion order`() = runTest {
        listDao.insert(TodoList(name = "Camping", position = 2))
        listDao.insert(TodoList(name = "Groceries", position = 0))
        listDao.insert(TodoList(name = "Household", position = 1))

        val names = listDao.getAll().first().map { it.name }

        assertEquals(listOf("Groceries", "Household", "Camping"), names)
    }

    @Test
    fun `getMaxPosition returns -1 on an empty table`() = runTest {
        // This is what COALESCE(MAX(position), -1) exists for: MAX over zero
        // rows is NULL, and the ViewModel adds 1 to get a first position of 0.
        assertEquals(-1, listDao.getMaxPosition())
    }

    @Test
    fun `getMaxPosition returns the highest position present`() = runTest {
        listDao.insert(TodoList(name = "a", position = 0))
        listDao.insert(TodoList(name = "b", position = 7))
        listDao.insert(TodoList(name = "c", position = 3))

        assertEquals(7, listDao.getMaxPosition())
    }

    @Test
    fun `insert assigns an autogenerated id`() = runTest {
        val rowId = listDao.insert(TodoList(name = "Groceries", position = 0))

        assertTrue("expected a generated id, got $rowId", rowId > 0)
        assertEquals(rowId.toInt(), listDao.getAll().first().single().id)
    }

    @Test
    fun `updateAll persists new positions`() = runTest {
        listDao.insert(TodoList(name = "Groceries", position = 0))
        listDao.insert(TodoList(name = "Household", position = 1))
        val stored = listDao.getAll().first()

        listDao.updateAll(stored.reversed().mapIndexed { i, l -> l.copy(position = i) })

        assertEquals(listOf("Household", "Groceries"), listDao.getAll().first().map { it.name })
    }

    // --- ChecklistDao ------------------------------------------------------

    @Test
    fun `getForList returns only that list's items, ordered by position`() = runTest {
        val groceries = listDao.insert(TodoList(name = "Groceries", position = 0)).toInt()
        val camping = listDao.insert(TodoList(name = "Camping", position = 1)).toInt()
        checklistDao.insert(ChecklistItem(listId = groceries, text = "Eggs", position = 1))
        checklistDao.insert(ChecklistItem(listId = camping, text = "Tent", position = 0))
        checklistDao.insert(ChecklistItem(listId = groceries, text = "Milk", position = 0))

        val texts = checklistDao.getForList(groceries).first().map { it.text }

        assertEquals(listOf("Milk", "Eggs"), texts)
    }

    @Test
    fun `getRemainingCounts counts only unchecked items`() = runTest {
        val groceries = listDao.insert(TodoList(name = "Groceries", position = 0)).toInt()
        checklistDao.insert(ChecklistItem(listId = groceries, text = "Milk"))
        checklistDao.insert(ChecklistItem(listId = groceries, text = "Eggs"))
        checklistDao.insert(ChecklistItem(listId = groceries, text = "Coffee", isChecked = true))

        val counts = checklistDao.getRemainingCounts().first()

        assertEquals(1, counts.size)
        assertEquals(groceries, counts.single().listId)
        assertEquals(2, counts.single().count)
    }

    @Test
    fun `a list whose items are all checked drops out of getRemainingCounts entirely`() = runTest {
        val groceries = listDao.insert(TodoList(name = "Groceries", position = 0)).toInt()
        checklistDao.insert(ChecklistItem(listId = groceries, text = "Milk", isChecked = true))

        val counts = checklistDao.getRemainingCounts().first()

        // The GROUP BY has no row to emit, so the list is absent rather than
        // present with 0. This is exactly why ListsViewModel needs `?: 0` —
        // without it, a fully checked-off list would vanish from the screen.
        assertTrue("expected no rows, got $counts", counts.isEmpty())
    }

    @Test
    fun `getMaxPosition is scoped per list`() = runTest {
        val groceries = listDao.insert(TodoList(name = "Groceries", position = 0)).toInt()
        val camping = listDao.insert(TodoList(name = "Camping", position = 1)).toInt()
        checklistDao.insert(ChecklistItem(listId = groceries, text = "Milk", position = 5))

        assertEquals(5, checklistDao.getMaxPosition(groceries))
        assertEquals(-1, checklistDao.getMaxPosition(camping))
    }

    // --- Due dates ---------------------------------------------------------

    @Test
    fun `a new item defaults to today's due date`() = runTest {
        val groceries = listDao.insert(TodoList(name = "Groceries", position = 0)).toInt()
        checklistDao.insert(ChecklistItem(listId = groceries, text = "Milk"))

        assertEquals(todayIso(), checklistDao.getForList(groceries).first().single().dueDate)
    }

    @Test
    fun `getForListByDueDate orders by date, falling back to position for ties`() = runTest {
        val household = listDao.insert(TodoList(name = "Household", position = 0)).toInt()
        checklistDao.insert(
            ChecklistItem(listId = household, text = "Later", position = 0, dueDate = "2026-09-01")
        )
        checklistDao.insert(
            ChecklistItem(listId = household, text = "TieB", position = 2, dueDate = "2026-08-18")
        )
        checklistDao.insert(
            ChecklistItem(listId = household, text = "TieA", position = 1, dueDate = "2026-08-18")
        )

        val texts = checklistDao.getForListByDueDate(household).map { it.text }

        assertEquals(listOf("TieA", "TieB", "Later"), texts)
    }

    @Test
    fun `setDueDatesEnabled flips the flag on only that list`() = runTest {
        val a = listDao.insert(TodoList(name = "Groceries", position = 0)).toInt()
        val b = listDao.insert(TodoList(name = "Household", position = 1)).toInt()

        listDao.setDueDatesEnabled(b, true)

        val byId = listDao.getAll().first().associateBy { it.id }
        assertEquals(false, byId.getValue(a).dueDatesEnabled)
        assertEquals(true, byId.getValue(b).dueDatesEnabled)
    }

    // --- Schema ------------------------------------------------------------

    @Test
    fun `deleting a list cascades to its items`() = runTest {
        val groceries = listDao.insert(TodoList(name = "Groceries", position = 0)).toInt()
        val camping = listDao.insert(TodoList(name = "Camping", position = 1)).toInt()
        checklistDao.insert(ChecklistItem(listId = groceries, text = "Milk"))
        checklistDao.insert(ChecklistItem(listId = camping, text = "Tent"))

        listDao.delete(listDao.getAll().first().single { it.id == groceries })

        assertTrue(checklistDao.getForList(groceries).first().isEmpty())
        // The other list is untouched.
        assertEquals(listOf("Tent"), checklistDao.getForList(camping).first().map { it.text })
    }
}
